name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Get latest version
        id: version
        run: echo "latest=$(./bin/latest-stable)" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4
        with:
          command: oxlint --version
          version: ${{ steps.version.outputs.latest }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Unit tests
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Setup Bats
        uses: bats-core/bats-action@472edde1138d59aca53ff162fb8d996666d21e4a # 2.0.0
        with:
          support-path: ${{ runner.temp }}/bats-support
          assert-path: ${{ runner.temp }}/bats-assert
          detik-path: ${{ runner.temp }}/bats-detik
          file-path: ${{ runner.temp }}/bats-file
      - name: Run unit tests
        run: bats test/*.bats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
